FROM apache/airflow:3.0.1

USER root

# Install docker-compose (or any other needed packages)
RUN apt-get update && \
    apt-get install -y --no-install-recommends docker-compose && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow

